markup:
  defaultMarkdownHandler: blackfriday
baseURL: 'https://www.mcmk.in'
languageCode: en-gb
defaultContentLanguage: en
title: mcmk.in
theme: hermit
enableGitInfo: true
pygmentsCodefences: true
pygmentsStyle: monokai
pygmentsUseClasses: true
rssLimit: 10
copyright: >-
  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
enableEmoji: true
canonifyurls: true
paginate: 10
googleAnalytics: UA-60607293-3
blackfriday:
  hrefTargetBlank: true
frontmatter:
  date:
    - date
    - publishDate
  lastmod:
    - ':git'
    - lastmod
  expiryDate: expiryDate
author:
  name: James McMeeking
taxonomies:
  tag: tags
  category: categories
params:
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04'
  themeColor: '#222'
  Description: 'Open source, automation, and tinkering.'
  Author: James McMeeking
  email: james@mcmk.in
  ShowReadTime: true
  contentTypeName: posts
  footerCopyright: ' &#183; <a href="https://opensource.org/licenses/MIT" target="_blank" rel="noopener">MIT</a>'
  gitUrl: 'https://github.com/mcmeeking/www.mcmk.in/commits/master/'
  justifyContent: false
  relatedPosts: true
  code_copy_button: true
  customCSS:
    - css/custom.css
  social:
    - name: linkedin
      url: 'https://www.linkedin.com/in/jmcmeeking91/'
    - name: github
      url: 'https://github.com/mcmeeking/'
    - name: email
      url: 'mailto:james@mcmk.in'
menu:
  main:
    - name: Posts
      url: posts/
      weight: 10
#    - name: CV
#      url: cv/
#      weight: 20
related:
  threshold: 80
  includeNewer: false
  toLower: false
  indices:
    - name: title
      weight: 100
    - name: tags
      weight: 30
